# Generated by Django 4.2.19 on 2026-02-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=12)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.kategori')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.status')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
    ]
